services:
  webserver:
    build:
      context: ./bin/php84
    container_name: "apacheweb"
#    restart: "always"
    networks:
      - apache-production
    ports:
      - "8081:80"
      - "8441:443"
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/html:rw
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${SSL_DIR-./config/ssl}:/etc/apache2/ssl/
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
      # - ${XDEBUG_LOG_DIR-./logs/xdebug}:/var/log/xdebug
    environment:
      PMA_PORT: ${HOST_MACHINE_PMA_PORT}
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT-/var/www/html}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      HOST_MACHINE_MYSQL_PORT: ${HOST_MACHINE_MARIADB_PORT}
      HOST_MACHINE_UNSECURE_HOST_PORT: ${HOST_MACHINE_UNSECURE_HOST_PORT}
  database:
    image: mariadb:12.1.2-ubi10
    container_name: "apachemariadb"
    networks:
      - apache-production
    ports:
      - "${HOST_MACHINE_MARIADB_PORT}:3306"
    volumes:
#      - ./config/initdb}:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
#      - ./config/mysql/my.cnf:/etc/mysql/conf.d
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
  phpmyadmin:
    image: phpmyadmin
    container_name: "apachephpmyadmin"
    networks:
      - apache-production
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
    ports:
      - "${HOST_MACHINE_PMA_PORT}:80"
      - "${HOST_MACHINE_PMA_SECURE_PORT}:443"
    volumes:
      - /sessions
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
  redis:
    container_name: "apacheredis"
    image: redis:latest
    networks:
      - apache-production
    ports:
      - "${HOST_MACHINE_REDIS_PORT}:6379"
networks:
  apache-production:
    # Use a custom driver
    driver: bridge